### ISSUE TITLE
Incopatible with newest version of IntelliJ

### ISSUE THREAD

**Issue by Xaver106** [kawamataryo/copy-git-link#13]
![image](https://user-images.githubusercontent.com/46501008/182347105-6878e8c2-8f4e-412a-95f8-7a09587e15f8.png)
![image](https://user-images.githubusercontent.com/46501008/182347422-c735989d-76a2-48cf-a08f-23e079e9ff62.png)

**Comment by kawamataryo** [comment]
Thank you for your issue. I will fix it as soon as possible.

**Comment by kawamataryo** [comment]
@Xaver106 

I fixed it. 
https://plugins.jetbrains.com/plugin/17756-copy-git-link/versions
