### ISSUE TITLE
Allow branch-link

### ISSUE THREAD

**Issue by guy4261** [kawamataryo/copy-git-link#17]
Instead of

`https://github.com/enterprise/project/blob/526e15a17869b5a3d718996b205c779bc82205f7/foo.py#L1`

Allow copying the link with the branch name instead of the blob SHA1

`https://github.com/enterprise/project/blob/main/foo.py#L1`

While this isn't a permalink it'd still be really useful!

**Comment by guy4261** [comment]
For example -

Instead of this permalink

https://github.com/kawamataryo/copy-git-link/blob/529dd42a10a0c588edd62edd0340f25ff438085c/src/main/kotlin/com/github/kawamataryo/copygitlink/utils/utils.kt#L34

I need this URL

https://github.com/kawamataryo/copy-git-link/blob/main/src/main/kotlin/com/github/kawamataryo/copygitlink/utils/utils.kt#L34

So this should change:

```diff
fun getPermalink(
    ...
-   return "https://github.com/$repositoryPath/blob/$revision$filePath$linePath"
-   return "https://github.com/$repositoryPath/blob/$branch$filePath$linePath"
```

With `branch` containing the currently checked out branch (output of `git branch --show-current`).

**Comment by kawamataryo** [comment]
Thank you for the issue.
I will be releasing a version soon that adds the `copy branch link` command!

**Comment by kawamataryo** [comment]
@guy4261 

I released v0.5.0. This version has a `copy branch link` command.
Please check it.

**Comment by guy4261** [comment]
Thanks! I got this with the update!

I'm on GitLab and oddly, while `Copy Permalink` works:

`https://{repo/user/project}/blob/a0dbb522fe996f18407ccbc497ed693ac3e06634/foo.py#L126`  
  
For the `Copy Branch Link` I get:  
  
`https://{repo/user/project}/blob/refs/heads/main/foo.py#L126`  
  
Which is bad. What I really need is   
  
`https://{repo/user/project}/blob/main/foo.py#L126`  
  
(no `refs/heads`). This still helps me a lot - thank you very much :bow: .

**Comment by scancmdr** [comment]
> Thanks! I got this with the update!
> 
> I'm on GitLab and oddly, while `Copy Permalink` works:
> 
> `https://{repo/user/project}/blob/a0dbb522fe996f18407ccbc497ed693ac3e06634/foo.py#L126`
> 
> For the `Copy Branch Link` I get:
> 
> `https://{repo/user/project}/blob/refs/heads/main/foo.py#L126`
> 
> Which is bad. What I really need is 
> 
> `https://{repo/user/project}/blob/main/foo.py#L126`
> 
> (no `refs/heads`). This still helps me a lot - thank you very much 🙇 .

I have the same issue, and this would also help me.
