### ISSUE TITLE
Incompatibility with 223.* IDEs

### ISSUE THREAD

**Issue by tocic** [kawamataryo/copy-git-link#18]
I got the following message with PyCharm 2022.3 (or CLion 2022.3):

> Plugin 'Copy Git Link' (version '0.3.5') is not compatible with the current version of the IDE, because it requires build 222.* or older but the current build is PY-223.7571.203

**Comment by kawamataryo** [comment]
Thank you for your issue.
I'll release the 223.* compatible version soon.

**Comment by kawamataryo** [comment]
@tocic 

I released v0.5.0. Please check it.

**Comment by tocic** [comment]
LGTM. Thank you for your work. Much appreciated.
