### ISSUE TITLE
Android Studio Arctic Fox (2020.3.1) support

### ISSUE THREAD

**Issue by mallowlabs** [kawamataryo/copy-git-link#2]
Hi.
Thank you for developing an awesome plugin!

I'm an Android developer.
I use Android Studio and I want to use this `copy-git-link` plugin.

But Android Studio is based on old IntelliJ platform.
For example, the latest stable release "Android Studio Arctic Fox (2020.3.1) Patch 3" is based on `203.7717.56`.
(ref: https://zenn.dev/kafumi/articles/3d01174cee8715 )

Can you change `pluginSinceBuild` to `203`?
I checked that it works on "Android Studio Arctic Fox (2020.3.1) Patch 3" with changed `pluginSinceBuild` version.

<img width="637" alt="arctic-fox" src="https://user-images.githubusercontent.com/19996/143239550-4ce41f28-5c3e-4314-b4b3-1e0a07e3ab8b.png">

**Comment by kawamataryo** [comment]
@mallowlabs 

Wow ! mallowlabs san !! Thanks for using my plugin XD.
I fixed to `pluginSinceBuild` to `203.*`

https://github.com/kawamataryo/copy-git-link/commit/e28d1cd776ec0f9fa9ddf53429a930b61ae7c874

 But. failed the pre-release review.

<img width="1383" alt="Screen Shot 2021-12-05 at 5 41 11" src="https://user-images.githubusercontent.com/11070996/144728330-2c2c451c-a777-4697-94b8-049f6704e180.png">

It seems that the methods used notifications are not compatible with older versions.
We will fix it at the end of the year, so please wait a while 🙏

**Comment by mallowlabs** [comment]
@kawamataryo 

Thank you for your challenge!

> It seems that the methods used notifications are not compatible with older versions.

It is a bad news 😢 

> We will fix it at the end of the year, so please wait a while 🙏

If it breaks the current behavior, you don't have to change supporting versions.
I can wait the new version of Android Studio!

Thanks in advance 😄

**Comment by mallowlabs** [comment]
I have good news and bad news.

The good news is that [Android Studio Bumblebee](https://android-developers.googleblog.com/2022/01/android-studio-bumblebee-202111-stable.html) is released!
It is based on IntelliJ platform`2021.1.1`(`pluginSinceBuild` is `211`)

The bad news is that I still cannot install `copy-git-link` to Android Studio Bumblebee.
Could you challenge to change `pluginSinceBuild` to `211`?
I hope that the compatibility problem is solved 🙏

**Comment by kawamataryo** [comment]
I had missed the message.
Sorry for the late reply 🙏 

I will try again to change PluginSinceBuild.

**Comment by kawamataryo** [comment]
@mallowlabs 

Sorry I'm really late!
Changed `pluginSinceBuild` to `211.*` in ver 0.3.2.
Please try it 👍

**Comment by mallowlabs** [comment]
@kawamataryo 

Thank you for your work!

However I cannot install `0.3.2` to my Android Studio (Bumblebee) 😢 

The version is below:

<img width="639" alt="version" src="https://user-images.githubusercontent.com/19996/160281602-e5581637-979e-4612-97b8-3f9d8505faca.png">

The error message is below:

<img width="422" alt="error" src="https://user-images.githubusercontent.com/19996/160281302-bd627a92-992f-484f-9e47-0beb97f2714c.png">

I tried to make a patch.
When I removed the wildcard from `pluginSinceBuild`, the install was succeeded locally.

```diff
diff --git a/gradle.properties b/gradle.properties
index 1e51fbe..af00ca8 100644
--- a/gradle.properties
+++ b/gradle.properties
@@ -7,7 +7,7 @@ pluginVersion = 0.3.2

 # See https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html
 # for insight into build numbers and IntelliJ Platform versions.
-pluginSinceBuild = 211.*
+pluginSinceBuild = 211
 pluginUntilBuild = 221.*

 # Plugin Verifier integration -> https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl
```

But I don't understand the reason. 🤔

**Comment by kawamataryo** [comment]
Sorry I didn't check 🙏

Thanks for the patch !!
I will try to apply again with `pluginSinceBuild: 211` 🚀

**Comment by kawamataryo** [comment]
I'm sorry...
Since I changed the build, it still failed in the marketplace public review due to compatibility issues...

I am now contacting Jetbrains slack and support. Please wait.

![image](https://user-images.githubusercontent.com/11070996/161016172-88eeb420-7dfb-46b2-8aa0-13cb1f97af1f.png)

**Comment by mallowlabs** [comment]
Thank you for your hard work 😢 

If it breaks the current behavior, you don't have to change supporting versions yet.
I can wait the next version of Android Studio!

**Comment by kawamataryo** [comment]
@mallowlabs 

I contacted Jetbrains support and found a solution 👍 

v 3.3 is now available.
You should be able to install that one with Android Studio.
Please try it!

![image](https://user-images.githubusercontent.com/11070996/161628507-11c722cd-d591-4969-abb0-57788053c41e.png)

**Comment by mallowlabs** [comment]
@kawamataryo 

I installed copy-git-link to Bumblebee successfully!
You accelerated my team productivity.
Thank you!!
