### ISSUE TITLE
Make it compatible IntelliJ IDEA 2023.1 RC

### ISSUE THREAD

**Issue by koppor** [kawamataryo/copy-git-link#22]
When trying to install this plugin to IntelliJ IDEA 2023, it is not possible. The plugin homepage states following:

![image](https://user-images.githubusercontent.com/1366654/225841087-20e1dd83-d7cd-4e2d-8f7d-79343f51d261.png)

**Comment by Xaver106** [comment]
The Plugin always takes some  time to update. 
As far as I can see, just removing this line will fix this for future builds: [gradle.properties#L11](https://github.com/kawamataryo/copy-git-link/blob/main/gradle.properties#L11)

**Comment by kawamataryo** [comment]
@Xaver106 @koppor 
Thank you for your report.
I'll remove the `pluginUntilBuild`  property.

**Comment by kawamataryo** [comment]
@Xaver106 @koppor 

Today I've released v0.5.1, which is compatible with IntelliJ IDEA 2023.1 RC version. Please check it out.

**Comment by koppor** [comment]
Works! Thank you for the quick action taken!
