### ISSUE TITLE
Incompatible: Requires IDE build 233.* or earlier

### ISSUE THREAD

**Issue by TonisPiip** [kawamataryo/copy-git-link#24]
![image](https://user-images.githubusercontent.com/4086333/231402128-4d272cc0-3f93-40bf-8a69-34226d07a948.png)

:( Seems that this is not working on the newer version of pycharm. Is the latest build working, if we install manually?

**Comment by kawamataryo** [comment]
It seems to work in my environment 🤔 
 Please give me information on the reproduced environment.
![image](https://user-images.githubusercontent.com/11070996/231667998-e5fd1490-db7c-4adf-9759-31a48322cfd3.png)

My PyCharm Version is 2023.1
![image](https://user-images.githubusercontent.com/11070996/231668059-f3f857c0-e649-4fc7-a261-42c50d5020cf.png)

**Comment by kawamataryo** [comment]
@TonisPiip 
Your CopyGitLink version is 5.0. Please upgrade to version 5.1.
